import {IAsyncCall, ISetAsyncCall} from '~Root/types';

export const GET_MATCHES_REQUESTED = 'GET_MATCHES/REQUESTED';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES/SUCCESS';
export const GET_MATCHES_FAILURE = 'GET_MATCHES/FAILURE';

export const ASYNC_GET_MATCHES: IAsyncCall = {
  REQUESTED: GET_MATCHES_REQUESTED,
  SUCCESS: GET_MATCHES_SUCCESS,
  FAILURE: GET_MATCHES_FAILURE,
};

export const SET_DATA_MATCHES = 'DATA_MATCHES/SET';
export const ASYNC_SET_DATA_MATCHES: ISetAsyncCall = {
  SET: SET_DATA_MATCHES,
};
