import {IAsyncCall} from '~Root/types';

export const INITIALIZE_AUTH_REQUESTED = 'INITIALIZE_AUTH/REQUESTED';
export const INITIALIZE_AUTH_SUCCESS = 'INITIALIZE_AUTH/SUCCESS';
export const INITIALIZE_AUTH_FAILURE = 'INITIALIZE_AUTH/FAILURE';

export const ASYNC_INITIALIZE_AUTH: IAsyncCall = {
  REQUESTED: INITIALIZE_AUTH_REQUESTED,
  SUCCESS: INITIALIZE_AUTH_SUCCESS,
  FAILURE: INITIALIZE_AUTH_FAILURE,
};

export const VERIFY_EMAIL_REQUESTED = 'VERIFY_EMAIL/REQUESTED';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL/SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL/FAILURE';

export const SET_PROGRESS = 'SET_PROGRESS/SET';
export const CLEAR_PROGRESS = 'CLEAR_PROGRESS/CLEAR';

export const LOG_OUT_REQUESTED = 'LOG_OUT/REQUESTED';
export const LOG_OUT_SUCCESS = 'LOG_OUT/SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT/FAILURE';
