import {IAsyncCall} from '~Root/types';

export const REGISTER_REQUESTED = 'REGISTER/REQUESTED';
export const REGISTER_SUCCESS = 'REGISTER/SUCCESS';
export const REGISTER_FAILURE = 'REGISTER/FAILURE';

export const ASYNC_REGISTER: IAsyncCall = {
  REQUESTED: REGISTER_REQUESTED,
  SUCCESS: REGISTER_SUCCESS,
  FAILURE: REGISTER_FAILURE,
};

export const VERIFY_CODE_REQUESTED = 'VERIFY_CODE/REQUESTED';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE/SUCCESS';
export const VERIFY_CODE_FAILURE = 'VERIFY_CODE/FAILURE';

export const VERIFY_OTP_REQUESTED = 'VERIFY_OTP/REQUESTED';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP/SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP/FAILURE';
