import {BASE_COLORS, BASE_FONTS, BASE_STYLES, GlobalStyles} from '~Root/config';
import {Dimensions, Platform, StyleSheet} from 'react-native';

import {adjust} from '~Root/utils';

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;
export default StyleSheet.create({
  chatInternalHeader: {
    backgroundColor: BASE_COLORS.steelBlue,
  },
  imageProfile: {
    width: adjust(80),
    height: adjust(80),
    borderRadius: adjust(160),
  },
  chatUserInfo: {
    ...GlobalStyles.ml20,
    flex: 1,
  },
  itemCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnAsking: {
    ...GlobalStyles.pv5,
    ...GlobalStyles.ph5,
    backgroundColor: BASE_COLORS.forestGreenColor,
    borderRadius: adjust(100),
    fontFamily: BASE_FONTS.regular,
    fontSize: adjust(10),
    textAlign: 'center',
  },
  viewContainer: {
    ...GlobalStyles.pv5,
    ...GlobalStyles.ph10,
    backgroundColor: BASE_COLORS.oxleyColor,
    borderBottomLeftRadius: adjust(10),
    borderBottomRightRadius: adjust(10),
    alignSelf: 'center',
    width: '60%',
    alignItems: 'center',
  },
  contentContainer: {
    flex: 1,
  },
  relativeBlock: {
    position: 'relative',
    overflow: 'hidden',
  },
  askBoxAnimation: {
    backgroundColor: 'transparent',
    position: 'absolute',
    width: '100%',
    top: 0,
    left: 0,
    zIndex: 5,
  },
  askArrow: {
    marginTop: 2,
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationContainer: {
    ...GlobalStyles.ph15,
    backgroundColor: BASE_COLORS.aeroColor,
    alignItems: 'center',
  },
  viewAskContainer: {
    ...GlobalStyles.ph15,
    ...GlobalStyles.pv2,
    backgroundColor: BASE_COLORS.aeroColor,
    alignItems: 'center',
  },
  textNotification: {
    textAlign: 'center',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
    fontSize: 15,
    color: BASE_COLORS.eerieBlackColor,
  },
  textViewAsk: {
    textAlign: 'center',
    fontSize: 10,
  },
  messageContainer: {
    ...GlobalStyles.ph10,
    ...GlobalStyles.pv10,
    backgroundColor: BASE_COLORS.steelBlueColor,
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 99,
  },
  inputContainer: {
    ...GlobalStyles.mh15,
    ...GlobalStyles.ph10,
    flex: 1,
    backgroundColor: BASE_COLORS.whiteColor,
    borderRadius: adjust(100),
    alignItems: 'flex-start',
  },
  input: {
    fontWeight: '600',
    width: '100%',
    fontSize: adjust(12),
    padding: adjust(8),
  },
  box: {
    opacity: 0,
    overflow: 'hidden',
  },
  boxContent: {
    ...GlobalStyles.pb20,
    ...GlobalStyles.mb15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
  },
  boxContentChild: {
    width: '50%',
  },
  button: {
    ...GlobalStyles.pv5,
    ...GlobalStyles.ph10,
    borderWidth: adjust(2),
    borderColor: BASE_COLORS.whiteColor,
    backgroundColor: BASE_COLORS.steelBlueColor,
    borderRadius: adjust(50),
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonOutline: {
    ...GlobalStyles.pv5,
    ...GlobalStyles.ph5,
    backgroundColor: 'transparent',
    borderWidth: adjust(2),
    fontSize: screenWidth > 400 ? 12 : 11,
    borderColor: BASE_COLORS.whiteColor,
    borderRadius: adjust(50),
    alignItems: 'center',
    alignSelf: 'center',
  },
  newButtonOutline: {
    ...GlobalStyles.pv5,
    ...GlobalStyles.ph8,
    ...GlobalStyles.mh5,
    backgroundColor: BASE_COLORS.blackColor,
    color: BASE_COLORS.aeroColor,
    fontSize: 12,
    borderRadius: adjust(50),
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonSameLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: adjust(10),
  },
  textStyle: {
    color: BASE_COLORS.whiteColor,
    fontFamily: BASE_FONTS.semiBold,
    fontSize: adjust(12),
  },
  hamburger: {
    width: adjust(24),
    height: adjust(24),
  },
  imageButton: {
    ...GlobalStyles.pv15,
  },
  newHeader: {
    height: (screenHeight / 100) * 18,
  },
  roleText: {
    color: BASE_COLORS.whiteColor,
    fontFamily: BASE_FONTS.medium,
    fontSize: 14,
  },
  roleTextContainer: {
    paddingHorizontal: adjust(10),
    paddingVertical: adjust(6),
    height: 30,
    textAlign: 'center',
    position: 'relative',
  },
  askInfoBlue: {
    backgroundColor: BASE_COLORS.tealBlueColor,
  },
  rightContainer: {
    alignSelf: 'flex-end',
    backgroundColor: BASE_COLORS.antiFlashWhiteColor,
    borderBottomLeftRadius: adjust(10),
    paddingHorizontal: adjust(10),
    paddingVertical: adjust(6),
  },
  rightLabel: {
    backgroundColor: BASE_COLORS.antiFlashWhiteColor,
    borderBottomLeftRadius: adjust(10),
    paddingHorizontal: adjust(10),
    paddingVertical: adjust(6),
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 1,
  },
  itemContainer: {
    flex: 1,
  },
  locationContainer: {
    display: 'flex',
    flexDirection: 'row',
    flex: 0.9,
    alignItems: 'center',
  },
  locationText: {
    flex: 0.9,
  },
  dateContainer: {
    display: 'flex',
    flexDirection: 'row',
    flex: 0.9,
    alignItems: 'center',
  },
  tagStyleContainer: {
    borderRadius: 10,
    backgroundColor: BASE_COLORS.aeroColor,
    fontFamily: BASE_FONTS.semiBold,
    alignSelf: 'flex-start',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  tagMaxWidth: {
    maxWidth: '75%',
  },
  tagStyle: {
    color: BASE_COLORS.eerieBlackColor,
    fontFamily: BASE_FONTS.semiBold,
    textTransform: 'capitalize',
  },
  labelEndStyle: {
    color: BASE_COLORS.whiteColor,
    fontFamily: BASE_FONTS.semiBold,
    textTransform: 'capitalize',
  },
  askEndStyleContainer: {
    borderRadius: 10,
    backgroundColor: BASE_COLORS.redColor,
    fontFamily: BASE_FONTS.semiBold,
    marginLeft: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    display: 'flex',
    justifyContent: 'center',
  },
  textNormal: {
    fontFamily: BASE_FONTS.medium,
    fontSize: BASE_STYLES.h5,
    lineHeight: 24,
    color: BASE_COLORS.whiteColor,
  },
  textBold: {
    fontFamily: BASE_FONTS.bold,
    fontSize: BASE_STYLES.h5,
    lineHeight: 24,
    color: BASE_COLORS.whiteColor,
  },
  count: {
    ...GlobalStyles.ph5,
    borderRadius: adjust(25),
    backgroundColor: BASE_COLORS.indianRedColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    minWidth: 25,
    marginTop: -5,
    marginLeft: 15,
  },
  notificationBlock: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  notificationCount: {
    ...GlobalStyles.ph5,
    borderRadius: adjust(25),
    backgroundColor: BASE_COLORS.indianRedColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    minWidth: 30,
    marginLeft: 10,
  },
  countText: {
    color: BASE_COLORS.whiteColor,
  },
  countNotificationText: {
    color: BASE_COLORS.whiteColor,
    fontSize: 14,
  },
  avatarContainer: {
    overflow: 'hidden',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'relative',
  },
});
