export const ON_CHANGE_PURPOSE_OF_ASK_REQUESTED = 'ON_CHANGE_PURPOSE_OF_ASK/REQUESTED';
export const ON_CHANGE_PURPOSE_OF_ASK_SUCCESS = 'ON_CHANGE_PURPOSE_OF_ASK/SUCCESS';
export const ON_CHANGE_PURPOSE_OF_ASK_FAILURE = 'ON_CHANGE_PURPOSE_OF_ASK/FAILURE';

export const GET_ASK_DROPDOWN_REQUESTED = 'GET_ASK_DROPDOWN/REQUESTED';
export const GET_ASK_DROPDOWN_SUCCESS = 'GET_ASK_DROPDOWN/SUCCESS';
export const GET_ASK_DROPDOWN_FAILURE = 'GET_ASK_DROPDOWN/FAILURE';

export const CREATE_ASK_REQUESTED = 'CREATE_ASK/REQUESTED';
export const UPDATE_ASK_REQUESTED = 'UPDATE_ASK/REQUESTED';
export const CREATE_ASK_SUCCESS = 'CREATE_ASK/SUCCESS';
export const CREATE_ASK_FAILURE = 'CREATE_ASK/FAILURE';

export const GET_ASK_SUBMISSIONS_REQUESTED = 'GET_ASK_SUBMISSIONS/REQUESTED';
export const GET_ASK_SUBMISSIONS_SUCCESS = 'GET_ASK_SUBMISSIONS/SUCCESS';
export const GET_ASK_SUBMISSIONS_FAILURE = 'GET_ASK_SUBMISSIONS/FAILURE';

export const GET_ASK_BY_REF_ID_REQUESTED = 'GET_ASK_BY_REF_ID/REQUESTED';
export const GET_ASK_BY_REF_ID_SUCCESS = 'GET_ASK_BY_REF_ID/SUCCESS';
export const GET_ASK_BY_REF_ID_FAILURE = 'GET_ASK_BY_REF_ID/FAILURE';

export const DESTROY_DATA = 'DESTROY_DATA/SET';

export const SET_ASK_SELECTED = 'ASK_SELECTED/SET';
export const SET_ASK_PREVIEW = 'ASK_PREVIEW/SET';

export const UPDATE_ASK_END_REQUESTED = 'UPDATE_ASK_END/REQUESTED';
export const UPDATE_ASK_END_SUCCESS = 'UPDATE_ASK_END/SUCCESS';
export const UPDATE_ASK_END_FAILURE = 'UPDATE_ASK_END/FAILURE';
