import {IAsyncCall} from '~Root/types';

export const LIST_MATCHES_REQUESTED = 'LIST_MATCHES/REQUESTED';
export const LIST_MATCHES_SUCCESS = 'LIST_MATCHES/SUCCESS';
export const LIST_MATCHES_FAILURE = 'LIST_MATCHES/FAILURE';

export const ASYNC_LIST_MATCHES: IAsyncCall = {
  REQUESTED: LIST_MATCHES_REQUESTED,
  SUCCESS: LIST_MATCHES_SUCCESS,
  FAILURE: LIST_MATCHES_FAILURE,
};

export const GET_CHAT_DATA_REQUESTED = 'GET_CHAT_DATA_REQUESTED';
export const GET_CHAT_DATA_SUCCESS = 'GET_CHAT_DATA_SUCCESS';
export const GET_PAGE_CHAT_DATA_SUCCESS = 'GET_PAGE_CHAT_DATA_SUCCESS';
export const UPDATE_CHAT_LAST_MESSAGE = 'UPDATE_CHAT_LAST_MESSAGE';
export const GET_CHAT_DATA_FAILURE = 'GET_CHAT_DATA_FAILURE';
export const UPDATE_CHAT_DATA = 'UPDATE_CHAT_DATA';
export const VIEW_CHAT_DETAIL = 'VIEW_CHAT_DETAIL';
export const GET_MESSAGE_DATA_REQUESTED = 'GET_MESSAGE_DATA_REQUESTED';
export const GET_MESSAGE_DATA_SUCCESS = 'GET_MESSAGE_DATA_SUCCESS';
export const GET_MESSAGE_DATA_FAILURE = 'GET_MESSAGE_DATA_FAILURE';
export const SEND_MESSAGE_REQUESTED = 'SEND_MESSAGE_REQUESTED';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const GET_ASK_DETAIL = 'GET_ASK_DETAIL';
export const GET_ASK_DETAIL_REQUEST = 'GET_ASK_DETAIL_REQUEST';
