export const industriesDefaultData = [
  '3D printing',
  'Accounting',
  'Advertising',
  'Agile processes',
  'Agritech',
  'Angel investing',
  'Artificial intelligence',
  'Autonomous & connected Vehicles',
  'B2B E-commerce',
  'B2B SaaS',
  'B2B sales',
  'Banking',
  'BFSI',
  'BioTech',
  'Blockchain',
  'Branding',
  'Business strategy',
  'Cleantech',
  'Cloud computing',
  'Coaching',
  'Community',
  'Compliances',
  'Construction',
  'Construction tech',
  'Consulting',
  'Content marketing',
  'Copywriting',
  'CRM',
  'Crypto',
  'Cybersecurity',
  'Data science',
  'Defense',
  'DeFi',
  'DevOps',
  'Digital design',
  'Digital marketing',
  'Digital publishing',
  'Digital transformation',
  'E-Commerce',
  'Edtech',
  'Email automation',
  'ERP',
  'Esports',
  'Fashion',
  'Finance',
  'Fintech',
  'FMCG',
  'Foodtech',
  'GameFi',
  'Gig economy',
  'Graphic design',
  'Growth hacking',
  'Health',
  'Health tech',
  'Hiring software engineering',
  'Hospitality tech',
  'HR partnering',
  'HR services',
  'HR tech',
  'Influencer marketing',
  'Insurance',
  'IoT',
  'IT services',
  'Lead generation',
  'Leadership development',
  'Legal services',
  'Legal&Compliance tech',
  'Life sciences',
  'LinkedIn',
  'Logistics',
  'Machine learning',
  'Manufacturing',
  'Marketing automation',
  'Marketing optimization',
  'Marketing services',
  'Marketplace',
  'Media',
  'Mentoring',
  'Metaverse',
  'Mindfulness',
  'Neuroscience',
  'NFT',
  'Nonprofit',
  'Not for profit',
  'PaaS',
  'Payments',
  'Personal branding',
  'Pharma',
  'Positive psychology',
  'Product development',
  'Product engineering services',
  'Product management',
  'product strategy',
  'Public relations',
  'Real estate tech',
  'Recruitment',
  'Remote working',
  'Retail',
  'Robotics',
  'Sale strategy',
  'Sales process',
  'SEO',
  'Social commerce',
  'Social media marketing',
  'Software engineering',
  'Sport tech',
  'Startup',
  'STEM',
  'Supply chain',
  'Sustainbility',
  'Talent acquisition',
  'Technology consulting',
  'Telco',
  'Telecom',
  'Training & development',
  'Travel tech',
  'User experience',
  'User interface',
  'UX research',
  'Venture capital',
  'Video games',
  'Virtual reality',
  'Waste management',
  'Wearable technology',
  'Workplace communication',
];
