export enum AppRoute {
  SPLASH = 'Splash',
  APP_CHECK = 'AppCheck',
  HOME = 'Home',
  YOUR_ASKS = 'Your asks',
  TRUST = 'Trust',
  HOME_DETAIL = 'HomeDetail',
  ASK_SHARE = 'AskShare',
  LOGIN = 'Login',
  PRIVACY = 'Privacy',
  INVITE_CODE = 'InviteCode',
  REGISTER = 'Register',
  RESET_PASSWORD = 'ResetPassword',
  FORGOT_PASSWORD = 'ForgotPassword',
  PROFILE = 'Profile',
  GUEST_PROFILE = 'GuestProfile',
  PROFILE_SECOND = 'ProfileSecond',
  CHAT = 'Chat',
  CHAT_INTERNAL = 'ChatInternal',
  CHAT_GENERAL_INTERNAL = 'ChatGeneralInternal',
  AIR_FEED = 'AIRFeed',
  TABS = 'Tabs',
  CREATE_ASK = 'CreateAsk',
  ASK_UPDATE = 'AskUpdate',
  ASK_PREVIEW = 'AskPreview',
  ASK_PUBLISH = 'AskPublish',
  VERIFY_EMAIL = 'VerifyEmail',
  VERIFIED_EMAIL = 'VerifiedEmail',
  RECOVER_PASSWORD = 'RecoverPassword',
  HOME_SHARE_SCREEN = 'HomeShare',
  ON_BOARDING_SCREEN = 'Onboarding',
  PROFILE_PERSONAL = 'ProfilePersonal',
  PROFILE_INDUSTRY = 'ProfileIndustry',
  INVITE_CONTACT = 'InviteContact',
  INVITE_REQUEST = 'InviteRequest',
  INVITE_CONTACT_EDIT = 'InviteContactEdit',
  LIST_CONTACT = 'ListContact',
  FEED_BACK_MODAL = 'FeedBackModal',
  INDIVIDUAL_MESSAGE_MODAL = 'IndividualMessageModal',
  JOINT_MESSAGE_MODAL = 'JointMessageModal',
  CHAT_CONTEXT_SWITCH = 'ChatContextSwitch',
  CHAT_NOTIFICATION_ASKER = 'ChatNotificationAsker',
  CHAT_NOTIFICATION_ASKER_REJECT_APPROVED = 'ChatNotificationAskerRejectApproved',
  CHAT_NOTIFICATION_INTRODUCER = 'ChatNotificationIntroducer',
  CHAT_NOTIFICATION_RESPONDER = 'ChatNotificationResponder',
  VIEW_PARTICIPANT = 'ViewParticipant',
  CLAIM_CODE = 'ClaimCode',
  RESET_PASSWORD_SUCCESS = 'ResetPasswordSuccess',
  RESENT_PASSWORD = 'ResentPassword',
}

export const AppRouteNotTabBar = {
  PROFILE_SECOND: 'ProfileSecond',
};
