export const GET_FEED_REQUESTED = 'GET_FEED/REQUESTED';
export const GET_FEED_SUCCESS = 'GET_FEED/SUCCESS';
export const GET_FEED_FAILURE = 'GET_FEED/FAILURE';

export const SET_QUESTION_FOR_FEED = 'SET_QUESTION_FOR_FEED';

export const CREATE_CHAT = 'CREATE_CHAT/REQUESTED';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT/SUCCESS';
export const CREATE_CHAT_FAILURE = 'CREATE_CHAT/FAILURE';

export const SET_INDEX_ASK = 'SET_INDEX_ASK';

export const CREATE_CHAT_INTRODUCE = 'CREATE_CHAT_INTRODUCE/REQUESTED';
export const CREATE_CHAT_INTRODUCE_SUCCESS = 'CREATE_CHAT_INTRODUCE/SUCCESS';
export const CREATE_CHAT_INTRODUCE_FAILURE = 'CREATE_CHAT_INTRODUCE/FAILURE';

export const SET_USER_TO_SHARE = 'SET_USER_TO_SHARE';

export const SET_NETWORK_TO_INTRODUCE = 'SET_NETWORK_TO_INTRODUCE';
